const texts = {
  version: `\n> *الإصدار:* OMRX \n> *المطور:* @omrxm`,
  test: `⛔⛔⛔`,
  privateMention: `#`,
  botDesc: `> *OMRX* not just a bot.`,
  botName: "OMRX",
  dev: "by @omrxm",
  isWorking: `OMRX Working\n`,
  defender: 'Error Defender: error has been caught and handled successfully.',
  errorIslid: `⚠️ *You are not allowed to do this in this group*`,
  spyTitle: ``,
  linkGenerated: "Link created:",
  notAdmin: `⚠️ *You are not an admin in this group!!*`,
  invalidLink: `⚠️ *Invalid link!!*`,
  checkGroupWithLinkTool: "*Group Link Checker V1*",
  linkedVmax: "*Link Check V-2*",
  linkedCheck: "*Linked Links Check*",
  warningBotLinked: "We may be linked to custom malicious bots.",
  subjectChanged: "Group subject changed",
  errorOnPlug: "Error during execution",
  errorIsNotGroup: "⚠️ *This command works only inside groups!!*",
  subjectInputError: `⚠️ *Group name must be between 1 and 69 characters!!*`,
  errorSameName: "⚠️ *You cannot use the same name, try a different name.*",
  parramsNotFound: "⚠️ *No settings found with that name.*",
  errorOnSwicher: "Error while switching mode",
  modeSwitched: "done..",
  adminsDemoted: "done..",
  adminsDemotedSuccessfully: "*done..*",
  groupUnlocked: "Oh",
  groupUnlockedSuccessfully: "*You may speak..*",
  grouplocked: "Please keep quiet..",
  grouplockedSuccessfully: "*⛔⛔..?*"
};

const emojis = {
  error: "🚫",
  success: "✅",
  info: "ℹ️",
  warning: "⚠️",
  loading: "⏳",
  done: "✅",
  fail: "❌",
  bot: "🤖",
  down: "⬇️",
  up: "⬆️",
  check: "✔️",
  link: "🔗",
  empty: "📂",
  mention: "⛔",
  params: "⚙️",
  delete: "🗑️",
  lock: "🔒",
  unlock: "🔓"
};

module.exports = {
  texts,
  emojis,
};